monolog:
    channels: ["errorReport", "notifications"]
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!event', '!errorReport', '!notifications']
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        errorReport:
            type: stream
            level: debug
            path: '%kernel.logs_dir%/error_report_dev.log'
            channels: ['errorReport']
        notifications:
            type: stream
            level: debug
            path: '%kernel.logs_dir%/notifications_dev.log'
            channels: ['notifications']
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
