monolog:
    channels: ["crawler", "notifications"]
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!crawler', '!notifications']
        crawler:
            type: stream
            level: debug
            path: '%kernel.logs_dir%/crawler_prod.log'
            channels: ['crawler']
        notifications:
            type: stream
            level: debug
            path: '%kernel.logs_dir%/notifications_prod.log'
            channels: ['notifications']
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
